import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <nav className="fixed top-0 left-0 w-full z-8 bg-transparent text-white p-4">
          <div className="max-w-screen-xl mx-auto flex justify-between items-center">

            <div className="text-2xl font-bold">Jason Sacerio</div>

                <div className="hidden md:flex space-x-6 absolute left-1/2 transform -translate-x-1/2">
                    <a href="/" className="hover:text-gray-300">Home</a>
                    <a href="/about" className="hover:text-gray-300">About</a>
                    <a href="/career" className="hover:text-gray-300">Career</a>
                    <a href="/projects" className="hover:text-gray-300">Projects</a>
                </div>
                    <div className="flex space-x-4">
                         <a
                            href="https://github.com/kwaiidev"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="hover:opacity-70 transition-opacity text-white"
                            aria-label="View GitHub Profile"
                         >
                    <img src="/github.svg" alt="GitHub" className="h-6 w-6 text-white" />
                     </a>
                     <a
                      href="https://www.linkedin.com/in/sacerio417/"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="hover:opacity-70 transition-opacity"
                      aria-label="View Linkedin Profile"
                       >
                      <img src="/linkedin.svg" alt="Linkedin" className="h-6 w-6" />
                    </a>
                    <a
                      href="/resume.pdf"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="hover:opacity-70 transition-opacity"
                      aria-label="View Resume"
                    >
                      <img src="/resume.svg" alt="resume" className="h-6 w-6" />
                    </a>
                    </div>
            </div>
          </nav>
          {children}
      </body>
    </html>
  );
}

